wiris/moodle-filter_wiris

filter.php
#52 
This fixes searching for the « character in a string that has upper case characters (Solaris, UTF-8, PHP 7.1.x)
=> PLUGINS-1255: Fix for multibyte stripos search

integration/lib/php/Boot.class.php, version.php
On the Moodle plugin install procedure, this error message appears to the user:
`Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/minh.edu.vn/filter/wiris/integration/lib/php/Boot.class.php on line 221`
**Expected behaviour:**
The PHP warning message should not appear to the user.
=> KB-3997: Fix a PHP warning  on Moodle plugin during the installation

version.php
The MathType moodle filter plugin and MathType for Atto versions don't match:
This can be checked on this moodle test:
- https://<moodle-address>/filter/wiris/info.php
**Solution**
There are no known incompatibililties between both plugins; everything works fine.
So it's only a matter of updating the version numbers to make them match.
A patch version upgrade is needed on the the affected repositories:
- atto_wiris
- tinymce_tiny_mce_wiris
- filter_wiris (this repo)
Close KB-3999
=> KB-3999: Upgrade MathType filter plugin version to match MathType for Atto/TinyMCE version

CHANGES.md, README.md, version.php
- Feature: 'Migrate MathType plugins suite from TravisCI to Github
Actions'.
- Add workflow based on 'moodle-plugin-ci'.
- Exclude phpunit test execution on Moodle3_10+.
- Remove TravisCI script from the project.
- Update .gitignore with custom paths.
- Update CHANGELOG
See: https://github.com/moodlehq/moodle-plugin-ci
- Fix lint issues on privacy class.
- Add full matrix to the tests
- Lint code on tests.
- Add Moodle .env variables.
=> Release 7.26.1 (18th june 2021)

CONTRIBUTING.md, README.md
On our last Engineering teams lead meeting, we decided to adopt the Conventional Commits specification to commit messages to all our source code projects.
This PR adds a new file called CONTRIBUTING.md to this project and it's referenced on the Contributing section of the main README file.
It describes the common best practices we plan to use in all our source code repositories that will adhere to this Commit message guidelines.
Also, this section aims to serve as a blueprint document that can be used on the "Contribution guidelines" documentation of every project.
The main benefits of this initiative are:
- Provide better information when browsing the history.
- Allow generating `CHANGELOG` by script.
- Allow ignoring commits by `git bisect`.
- Automatically determining a semantic …
=> docs: add support for conventional commits #KB-18015

CHANGES.md, classes/moodledbcache.php, classes/moodledbjsoncache.php, classes/moodlefilecache.php, classes/pluginwrapperconfigurationupdater.php, classes/privacy/provider.php, db/upgrade.php, lib.php, subfilters/client.php, subfilters/php.php, tests/filter_performance_png_test.php, tests/filter_performance_svg_test.php, tests/filter_without_performance_png_test.php, tests/filter_without_performance_svg_test.php
The dependency moodle-plugin-ci that we use to test and analyze our Moodle suit projects code, has been updated to 3.2.3, introducing the following changes:
- PHP_CodeSniffer upgraded to 3.6.2 release (see: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.6.2)
- Report unexpected MOODLE_INTERNAL uses (see: https://github.com/moodlehq/moodle-local_codechecker/pull/169)
This change affects directly to our GitHub Actions workflow, it makes it fail, hence it does not allow us to make new releases of the Moodle suite.
The new release of the moodle-plugin-ci dependency claims that, all PHP files without side-effects must remove unnecessary `MOODLE_INTERNAL` requirements.
```php
defined('MOODLE_INTERNAL') || die();
```
This PR also includes:
- There are also other linting issues that …
=> CI/CD Pipeline is broken: fix code checker

.github/workflows/moodle-ci.yml, tests/behat/checkThirdPartyLibs.feature, tests/behat/servicesNotLogged.feature, tests/behat/testClientRender.feature, tests/behat/testConnectionSettings.feature, tests/behat/testImageFormat.feature, tests/behat/testPerformanceDisabled.feature, tests/behat/testServerRenderSVG.feature
The main goal of this task is to make all Behat test compatible with Moodle 4.0 branch. Also the tests are compatible with the previous Moodle (3.x)  supported  version.
1. Go to [moodle-filter_wiris github repository Actions section.](https://github.com/wiris/moodle-filter_wiris/actions)
3. Select the `Moodle Plugin CI` workflow.
4. Click on `Run workflow` and select the branch `moodle40`.
5. Click on the `Run workflow` green button.
---
[#taskid 21988](https://wiris.kanbanize.com/ctrl_board/2/cards/21988/details/)
=> Filter plugin behat tests compatibility with Moodle 4.0 

filter.php, integration/lib/com/wiris/plugin/impl/TextFilter.class.php, tests/behat/behat_wiris_filter.php, tests/behat/urlToLinkFilterCompatibility.feature, thirdpartylibs.xml
Recently, a client complained that the EReg class was raising warnings due to the same-named class being obsolete. We agreed on removing the usage of the class altogether.
EReg is used for pattern matching. Fortunately this was only used in one relevant spot in the Moodle filter integration, making it easy to move the logic from the transpiled part to the PHP native part (see `filter.php`).
To test this change, make sure that the newly added Behat test is well defined and passes correctly, and that the newly implemented code accurately recreates the logic of the old commented code.
Edit: it should be noted that this version of the filter is using a version of the backend integration that is NOT YET published (7.29.0).
=> fix: Stop using obsolete EReg in transpiled PHP 

info.php
There's an error with the links on the Moodle info page, as in the image below:
This PR fixes the broken links with the right ones that include UTMs
---
[taskid 23200](https://wiris.kanbanize.com/ctrl_board/2/cards/23200/details/)
=> Fix moodle test info page links

.github/workflows/moodle-ci.yml, settings.php
The old default value for this setting was invalid (it used to say `default`).
1. Open a Moodle instance with the filter on this branch.
2. As an admin, go to the Settings > Filters > MathType filter page, and look for the "Render type" setting.
3. It should have a string beside the dropdown box saying "Default: PHP".
=> fix: Set default value to PHP for rendertype setting

tests/behat/testClientRender.feature, tests/behat/testServerRenderPNG.feature, tests/behat/testServerRenderSVG.feature, tests/behat/urlToLinkFilterCompatibility.feature
##Description
Moodle is releasing the 4.1 version. This PR includes the changes on the moodle filter tests so that they can be compatible with the latest updates.
1. Follow the instructions on the `wiris-moodle-docker` project to create a new moodle with
* The moodle branch set to `master`.
* The wiris moodle branch set to `KB-28918`.
2. Run the tests with the tag `filter_wiris`
---
[#taskid 28918](https://wiris.kanbanize.com/ctrl_board/2/cards/28918/details/)
=> Update tests for Moodle 4.1

classes/pluginwrapper.php
With the TinyMCE Legacy deprecation, there are some routes that the project expected, which now don't exist in Moodle 4.2 and above. This PR fixes the routes and adds retro-compatibility for moodle 4.1 and lower.
1. Open a Moodle with the 4.2 version.
2. Go to the administration panel. 
3. Validate that no error appears.
4. Do the same for a lower version than 4.2 to validate the retro-compatibility.
---
[#taskid 35385](https://wiris.kanbanize.com/ctrl_board/2/cards/35385/details/)
Closes #121
=> Update MCE Legacy routes

classes/configurationupdater.php, integration/lib/com/wiris/plugin/impl/ConfigurationImpl.class.php, integration/lib/default-configuration.ini
The Telemetry events were not sending the correct Moodle course and category. Those were sent by the back-end, and were set just once, when the filter is loaded, which caused the values to never change from their original value.
This PR removes the previous way of sending the Moodle course data to Telemetry, which used the backend configuration.
* Validate that there are no configurations defined to send the course data to Telemetry or the front-end.
---
[#taskid 34608](https://wiris.kanbanize.com/ctrl_board/2/cards/34608/details/)
=> Moodle not sending the correct course and category to Telemetry

.github/workflows/moodle-ci.yml, classes/pluginwrapper.php, info.php, lang/en/filter_wiris.php, settings.php, test.php, tests/behat/behat_wiris_editor.php, tests/behat/behat_wiris_filter.php
This PR fix two bugs when you have a Moodle with MathType for TinyMCE6 without MathType for Atto:
1. The some configuration properties from filter configuration page disappear.
2. The info.php page display three errors because doesn't find the atto plugin.
1. Open Moodle 4.2 with php 8.2` using wiris-moodle-docker` project.
2. Delete MathType for Atto deleting the folder `<Moodle-path>/lib/editor/atto/plugins/wiris`.
3. Login as admin an go to the [MathType Filter Administration Page](http://localhost:8000/admin/settings.php?section=filtersettingwiris)
All configuration properties must appear
4. Navigate to [http://localhost:8000/filter/wiris/info.php](http://localhost:8000/filter/wiris/info.php)
A table will be rendered as the next image without any warning message on the top of the page …
=> [KB-37848] Fix bugs when "MathType filter + MathType for TinyMCE 6" installed withour the MathType for ATTO.

.github/workflows/moodle-cd.yml
In this PR the github actions workflows are updated so the outputs are stored correctly, following these instructions https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Associated KB card: https://wiris.kanbanize.com/ctrl_board/2/cards/34039/details/
=> [KB-34039] Update how steps output are store in Github actions workflows.

info.php, lang/en/filter_wiris.php, settings.php
This PR add the next warning message on `settings.php` and `info.php` page if the TinyMCE (Legacy) plugins is installed in Moodle version 4.2 or highest.
```
MathType for TinyMCE (legacy) is not supported in Moodle 4.2 or higher, you must uninstall the plugin located on "./lib/editor/tinymce/plugins/tiny_mce_wiris" and install the MathType plugin for TinyMCE 6
```
1. Open a Moodle 3.10.
2. Increase Moodle version to 4.2
3. Check info.php page (http://localhost:8000/filter/wiris/info.php) If the warning appears.
4. Check info filter settings page (http://localhost:8000/admin/settings.php?section=filtersettingwiris) If the waning appears.
5. On Moodle remove the folder "./lib/editor/tinymce/" folder and check if the warning disappear on info.php and filter settings page.
---
[#taskid …
=> feat: add notification tinymce legacy incompatibility

settings.php
Fix error for MathType for TinyMCE (legacy) warning, that can be displayed multiple times on the Site administration.
(If this is your first time running Moodle, please following this instruction to configure: https://github.com/wiris/wiris-moodle-docker/blob/main/README.md)
1. Use Moodle > 4.1.
2. MathType for TinyMCE (legacy) is installed
3. Log in Moodle as an admin
4. Go to Site Administration
5. Go to Plugins > Filter > MathType by WIRIS
6. Change Render Type from Client to PHP.
7. Check that the warning only shows one time
---
[taskid 44423](https://wiris.kanbanize.com/ctrl_board/2/cards/44423/details/)
=> Fetch notification when load setting page

tests/behat/behat_wiris_editor.php
Fix test:
Deleted step to press on Cancel button
Fixed “Cancel button” function (it was pressing accept button)
Added function to check if ChemType is opened instead of MathType and changed the verification after opening it. Updated a few tests that were using the MT function instead of the CT function
https://wiris.kanbanize.com/ctrl_board/2/cards/50411/details/
=> test: fix MTMOODLE-90

tests/behat/urlToLinkFilterCompatibility.feature
The test is to check that urlToLink is incompatible with MT, but instead of activating it, it was deactivating it.
Tested in 4.3 and it worked (which is unexpected).
=> MTMOODLE-30: Fix

subfilters/php.php
Avoid transforming LaTeX in editing context to prevent unnecessary rendering requests.
Editors may inject the string "$$\pi$$" during tests, which previously caused excessive rendering requests.
This check ensures that the string "$$\pi$$" is not transformed by the service.
=> fix: prevent unnecessary LaTeX rendering during editing context
